name: Build and run maven project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Maven build
      run: mvn compile
    - name: Run App
      run: cd target/classes && java ste.mvntest.App